# Generated by Django 6.0.6 on 2026-06-22 14:54

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=product.models.get_default_cat, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
